[package]
name = "kurogane-suite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
cef.workspace = true
kurogane = { workspace = true }
serde_json = "1.0.149"
winit = "0.30"
raw-window-handle = "0.6"

[dev-dependencies]
tempfile = "3"
git2 = "0.21"

[[example]]
name = "benchmark"
path = "scenarios/benchmark/main.rs"

[[example]]
name = "gpu"
path = "scenarios/gpu/main.rs"

[[example]]
name = "files-cors"
path = "scenarios/files-cors/main.rs"

[[example]]
name = "dom"
path = "scenarios/dom/main.rs"

[[example]]
name = "pump"
path = "scenarios/pump.rs"

[[example]]
name = "css-to-shader"
path = "scenarios/css-to-shader/main.rs"

[[example]]
name = "ipc"
path = "scenarios/ipc/main.rs"

[[example]]
name = "wasm"
path = "scenarios/wasm/main.rs"

[[example]]
name = "winit_views_poll"
path = "winit/views_poll.rs"

[[example]]
name = "winit_views_timer"
path = "winit/views_timer.rs"

[[example]]
name = "winit_views_scheduler"
path = "winit/views_scheduler.rs"

[[example]]
name = "winit_native_embedding"
path = "winit/host_window.rs"

[[example]]
name = "popups"
path = "scenarios/popups/main.rs"

[[example]]
name = "multi-window"
path = "scenarios/multi-window.rs"

[[example]]
name = "window-management"
path = "scenarios/window-management.rs"

[[example]]
name = "delegates"
path = "scenarios/delegates.rs"

[[example]]
name = "stream-benchmark"
path = "scenarios/stream-benchmark/main.rs"

[[example]]
name = "sandbox-smoke"
path = "scenarios/sandbox-smoke.rs"

[[example]]
name = "workspace"
path = "scenarios/workspace/main.rs"

[[example]]
name = "menu"
path = "scenarios/menu/main.rs"
